### ISSUE TITLE
Nginx fastcgi_cache purge all

### ISSUE THREAD

**Issue by rahul286** [rtCamp/nginx-helper#10]
Option to delete entire cache

**Comment by xoogu** [comment]
I've read elsewhere that simply unlinking the cache files will result in nginx recording an error when it tries to access the cached file, since the key is not also removed from nginx's cache.

If the ngx_cache_purge module had support to purge an entire zone, as you requested, it would be much better. But in the meantime, have you considered modifying the plugin so that it makes a request to the purge URL for each of the pages in the cache?

You'd need to initially store the cache key for each page, along with the page id in a db table. Then for a full purge, loop through the nginx cache folder, getting the keys of all cached files. Lookup the keys in your db table, thus allowing you to get the URL for each key. Then call the purge URL for each of the cached URLs.

I'm not sure how expensive requesting the purge URL 100s or even 1000s of times in quick succession would be though. So long as PHP and Nginx are on the same machine there shouldn't be any network latency.

**Comment by rahul286** [comment]
@xoogu to solve this and few other limitations we added redis full-page cache feature in EasyEngine - https://rtcamp.com/blog/easyengine-3-3-full-page-redis-cache/ .

If you are not using EasyEngine, you may do a manual nginx setup by following - https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/

As we have moved to a different workaround, we will unlikely spend any more time working on this.
