### ISSUE TITLE
Multisite Purge All Not Working

### ISSUE THREAD

**Issue by jwogrady** [rtCamp/nginx-helper#133]
I have WP multisite setup.  The pages are purged on content updates, but the purge button in the menu bar and the red global site purge button do not work.  My assumption this is permissions related... perhaps the nginx user and php user are different?   Nginx says www-date and the php-fpm www pool config says owner and group are www-data.  Is there another place I might look?

**Comment by jwogrady** [comment]
Well, I tried 777 the entire directory to see if the files would delete.   That didn't work.   I restored and back to the defaults....

`drwx------  5 www-data root      100 Jan  6 00:35 nginx-cache`
````nginx-cache/
├── [www-data www-data]  8
│   └── [www-data www-data]  c0
│       └── [www-data www-data]  a7a2513f60b3e8d33391feaddfd55c08
├── [www-data www-data]  5
│   ├── [www-data www-data]  4a
│   │   └── [www-data www-data]  04613abb8e65a34754c5be172768e4a5
│   └── [www-data www-data]  38
│       └── [www-data www-data]  ec4cd6c9f134be5e7efc874a57950385
└── [www-data www-data]  3
    └── [www-data www-data]  3f
        └── [www-data www-data]  4d71bb0d043d13d36f2a315abbd1b3f3
````

Again, when I use the manual page url the files deletes.  Only having problems with the buttons.

**Comment by kingkool68** [comment]
I would turn on logging and see if you see the message `Let's purge everything!` and `Everthing purged!` shows up.

See https://github.com/rtCamp/nginx-helper/blob/b390519b51fe71d645d1c13ab1afe4127c4c4078/purger.php#L706-L723

**Comment by nserev** [comment]
Just a note here, because I think I am experiencing the same issue. When php-fpm and nginx are running with different users the module always gives permission denied in case cache is being purged.

2017/03/13 14:49:40 [error] 28052#28052: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  opendir(/tmp/cache): failed to open dir: Permission denied in /var/www/public/wp-content/plugins/nginx-helper/purger.php on line 772" while reading response header from upstream, client: 127.0.0.1, server: example.com, request: "GET /wp-admin/options-general.php?page=nginx&nginx_helper_action=purge&nginx_helper_urls=all&_wpnonce=4a338cd144 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "example.com", referrer: "http://example.com/wp-admin/options-general.php?page=nginx"

**Comment by mrrobot47** [comment]
Closing as this seems to be issue with different users in php and nginx. Not an issue in plugin.
