### ISSUE TITLE
"Purge Cache" execution when sidebar widgets are modified.

### ISSUE THREAD

**Issue by rahul286** [rtCamp/nginx-helper#48]
We need to add a new purge option.

Refer - http://wordpress.org/support/topic/purging-after-widget-changes?replies=4

**Comment by chandrapatel** [comment]
Users can purge all the cache from plugin settings so I believe we don't need to give an another option. Also, that option may not be very common for end users because widgets may only used on some post types, and not all post types and purging the entire cache when widgets updated will be not good for some end users.

**Comment by rahul286** [comment]
Good point @chandrapatel  👍 

Looking back I feel that was an attempt to over-optimize
